account/urls.py
from django.urls import path, include
from . import views

app_name = 'job'
urlpatterns = [

    path('signup', views.signup, name = 'signup'),
    path('profile', views.profile_h, name = 'profile'),
    path('profile_edit', views.profile_edit, name = 'profile_edit'),

]

job/urls.py
from django.urls import path, include
from . import views

app_name = 'job'
urlpatterns = [

    path('', views.job_list, name = 'job_list'),
    path('add', views.add_job, name ='add_job' ),
    path('<str:slug>', views.job_delail, name ='job_detail' ),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('account.urls', namespace= 'account')),
    path('admin/', admin.site.urls),
    path('jobs/', include('job.urls',namespace= 'jobs')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.ForeignKey('City', related_name='user_city', on_delete=models.CASCADE , blank=True, null=True)
    phone_number = models.CharField(max_length=15)
    image  = models.ImageField(upload_to='profile/')


    def __str__(self):
        return str(self.user)

## create new user ---> create new empty profile


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)



class City(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

blog/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

job/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.

# title - location - job type - description - published at - Vacancy - salary - category - experience

job_option = (
    ('full time','full time'),
    ('part time','part time'),
)

def image_upload(instance, filename):
    imagename , extention = filename.split(".") 
    return "job/%s.%s"%(instance.id,extention)


class job (models.Model):
    owner = models.ForeignKey(User , related_name='job_owner', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    job_type = models.CharField(max_length=50, choices=job_option)
    description = models.TextField(max_length=1000)
    published_at = models.DateTimeField(auto_now= True)
    Vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=0)
    experience = models.IntegerField(default=1)
    category = models.ForeignKey('categorys', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload)
    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(job,self).save(*args, **kwargs)

    def __str__(self):
        return self.title

class categorys (models.Model):
    name = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now= True)
    def __str__(self):
        return self.name  


class applayer(models.Model):
    job = models.ForeignKey(job, related_name='apply_job', on_delete=models.CASCADE)
    name = models.CharField( max_length=50)
    email = models.EmailField( max_length=254)
    site = models.URLField( max_length=200)
    cv = models.FileField(upload_to= '')
    cover_letter = models.TextField(max_length= 1000)

    def __str__(self):
        return self.name

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class Singup_form (UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class pro_edit(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('__all__')
        
class us_edit(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ("first_name","last_name")

job/forms.py
from django import forms
from .models import applayer , job

class apply(forms.ModelForm):
    class Meta:
        model = applayer
        fields = ( "name" , "email" , "site" , "cv" , "cover_letter")

class add (forms.ModelForm):
    class Meta:
        model = job
        fields = ('__all__')
        exclude = ('slug', 'owner')

account/views.py
from django.shortcuts import redirect, render
from .forms import Singup_form , pro_edit , us_edit
from django.contrib.auth import authenticate, login
from .models import Profile
from django.urls import reverse
# Create your views here.

def signup(request):
    if request.method=="POST":
        form = Singup_form(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect('/accounts/profile')
    else:
        form = Singup_form()
    return render(request,'registration/signup.html',{'form':form})



def profile_h(request):

    profile_data = Profile.objects.get(user=request.user)
    return render(request, 'accounts/profile.html', {'profile':profile_data })


def profile_edit(request):
    profile = Profile.objects.get(user=request.user)
    msg = ''
    if request.method == 'POST':
        form_profile = pro_edit(request.POST , request.FILES ,instance=profile)
        form_user = us_edit(request.POST , instance=request.user)
        if form_profile.is_valid() and form_user.is_valid():
            form_user.save()
            form_data = form_profile.save(commit=False)
            form_data.user = request.user
            form_data.save()
        return redirect(reverse('account:profile'))

    else:
        form_profile = pro_edit(instance=profile)
        form_user = us_edit(instance=request.user)
    return render(request, 'accounts/profile_edit.html', { 'form_u':form_user , 'form_p':form_profile,'msg':msg} )

blog/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render

# Create your views here.

job/views.py
from django.shortcuts import render , redirect
from .models import job 
from django.core.paginator import Paginator
from .forms import apply , add
from django.urls import reverse

# Create your views here.

def job_list (request):
    job_list = job.objects.all()
    paginator = Paginator(job_list, 1) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'jobs' : page_obj ,
    }
    return render(request, 'job/job_list.html', context)


def job_delail(request, slug):
    job_delail = job.objects.get(slug=slug)
    
    if request.method == 'POST' :
        form = apply(request.POST , request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            data.job = job_delail
            data.save()
    else :
        form = apply()


    context = {
        'job' : job_delail , 'forms' : form ,
    }
    return render(request, 'job/job_detail.html' , context)

def add_job (request):

    if request.method == 'POST':
        form = add(request.POST , request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            data.owner = request.user
            data.save()
            return redirect(reverse('jobs:job_list'))
    else :
        form = add()
    
    context = {
        'form': form 
    }
    return render(request, 'job/add_job.html', context)

account/templates/accounts/profile.html
{% extends "base_generic.html" %}
{% load bootstrap4 %}
{% block content %}


<h1> {{profile.user.email}} </h1>
<h1> {{profile.city}} </h1>
<h1> {{profile.phone_number}} </h1>
<h1> {{profile.image.url}} </h1>

<a href="profile_edit">edit</a>

{% endblock %}

account/templates/accounts/profile_edit.html
{% extends "base_generic.html" %}
{% load bootstrap4 %}
{% block content %}


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form_u %}
    {% bootstrap_form form_p %}
    <input type="submit" value="edit" />

</form>
<h1>{{msg}}</h1>

{% endblock %}

job/templates/job/add_job.html
{% extends 'base.html' %}
{% block body %}
{% load bootstrap4 %}

	<div class="clearfix"></div>
	
	<!-- Title Header Start -->
	<section class="inner-header-title" style="background-image:url(assets/img/banner-10.jpg);">
		<div class="container">
			<h1> {{job.title}} </h1>
		</div>
	</section>
	<div class="clearfix"></div>
	<!-- Title Header End -->


	<section>
		<div>
			<form style="padding : 100px " method="post" class="form" enctype = "multipart/form-data">
				{% csrf_token %}
				{% bootstrap_form form %}
				{% buttons %}
					<button type="submit" class="btn btn-primary">Submit</button>
				{% endbuttons %}
			</form>
		</div>
	</section>
	<!-- Job full detail End -->
		
{% endblock body %}

job/templates/job/job_detail.html
{% extends 'base.html' %}
{% block body %}
{% load bootstrap4 %}

	<div class="clearfix"></div>
	
	<!-- Title Header Start -->
	<section class="inner-header-title" style="background-image:url(assets/img/banner-10.jpg);">
		<div class="container">
			<h1> {{job.title}} </h1>
		</div>
	</section>
	<div class="clearfix"></div>
	<!-- Title Header End -->
	
	<!-- Job Detail Start -->
	<section class="detail-desc">
		<div class="container white-shadow">
		
			<div class="row">
			
				<div class="detail-pic">
					<img src="" class="img" alt="" />
					<a href="#" class="detail-edit" title="edit" ><i class="fa fa-pencil"></i></a>
				</div>
				
				<div class="detail-status">
					<span> {{job.published_at|date:'d M Y'}} </span>
				</div>
				
			</div>
			
			<div class="row bottom-mrg">
				<div class="col-md-8 col-sm-8">
					<div class="detail-desc-caption">
						<h4>Google</h4>
						<span class="designation">Software Development Company</span>
						<p>{{job.description}}</p>
						<ul>
							<li><i class="fa fa-briefcase"></i><span> {{job.job_type}} </span></li>
							<li><i class="fa fa-flask"></i><span>{{job.experience}} Year Experience</span></li>
						</ul>
					</div>
				</div>
				
				<div class="col-md-4 col-sm-4">
					<div class="get-touch">
						<h4>Get in Touch</h4>
						<ul>
							<li><i class="fa fa-map-marker"></i><span>Menlo Park, CA</span></li>
							<li><i class="fa fa-envelope"></i><span>danieldax704@gmail.com</span></li>
							<li><i class="fa fa-globe"></i><span>microft.com</span></li>
							<li><i class="fa fa-phone"></i><span>0 123 456 7859</span></li>
							<li><i class="fa fa-money"></i><span>{{job.salary}}/Month</span></li>
						</ul>
					</div>
				</div>
				
			</div>
			
			<div class="row no-padd">
				<div class="detail pannel-footer">
					<div class="col-md-5 col-sm-5">
						<ul class="detail-footer-social">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
							<li><a href="#"><i class="fa fa-instagram"></i></a></li>
						</ul>
					</div>
					
					<div class="col-md-7 col-sm-7">
						<div class="detail-pannel-footer-btn pull-right">
							<a href="#" class="footer-btn grn-btn" title="">Quick Apply</a>
							<a href="#" class="footer-btn blu-btn" title="">Save Draft</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Job Detail End -->
	
	<!-- Job full detail Start -->
	<section class="full-detail-description full-detail">
		<div class="container">
			<div class="row row-bottom">
				<h2 class="detail-title">Job Responsibilities</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
			</div>
			
			<div class="row row-bottom">
				<h2 class="detail-title">Skill Requirement</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
				<ul class="detail-list">
					<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor</li>
					<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</li>
					<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</li>
					<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</li>
					<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</li>
					<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.</li>
					<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.</li>
				</ul>
			</div>
			
			<div class="row row-bottom">
				<h2 class="detail-title">Qualification</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
				<ul class="detail-list">
					<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor</li>
					<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</li>
					<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</li>
					<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</li>
					<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</li>
					<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.</li>
					<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do.</li>
					<li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
				</ul>
			</div>
			
		</div>
	</section>


	<section>
		<div>
			<form style="padding : 100px " method="post" class="form" enctype = "multipart/form-data">
				{% csrf_token %}
				{% bootstrap_form forms %}
				{% buttons %}
					<button type="submit" class="btn btn-primary">Submit</button>
				{% endbuttons %}
			</form>
		</div>
	</section>
	<!-- Job full detail End -->
		
{% endblock body %}

job/templates/job/job_list.html
{% extends 'base.html' %}
{% block body %}	
	<!-- Title Header Start -->
	<section class="inner-header-title" style="background-image:url(assets/img/banner-10.jpg);">
		<div class="container">
			<h1>Browse Jobs</h1>
		</div>
	</section>
	<div class="clearfix"></div>
	<!-- Title Header End -->
	
	<!-- ========== Begin: Brows job Category ===============  -->
	<section class="brows-job-category">
		<div class="container">
			<!-- Company Searrch Filter Start -->
			<div class="row extra-mrg">
				<div class="wrap-search-filter">
					<form>
						<div class="col-md-4 col-sm-4">
							<input type="text" class="form-control" placeholder="Keyword: Name, Tag">
						</div>
						<div class="col-md-3 col-sm-3">
							<input type="text" class="form-control" placeholder="Location: City, State, Zip">
						</div>
						<div class="col-md-3 col-sm-3">
							<select class="selectpicker form-control" multiple title="All Categories">
								<option>Information Technology</option>
								<option>Mechanical</option>
								<option>Hardware</option>
							</select>

						</div>
						<div class="col-md-2 col-sm-2">
							<button type="submit" class="btn btn-primary">Filter</button>
						</div>
					</form>
				</div>
			</div>
			<!-- Company Searrch Filter End -->
			
			{% for job in jobs %}
				<div class="item-click">
					<article>
						<div class="brows-job-list">
							<div class="col-md-1 col-sm-2 small-padding">
								<div class="brows-job-company-img">
									<a href="job-detail.html"><img src="assets/img/com-1.jpg" class="img-responsive" alt="" /></a>
								</div>
							</div>
							<div class="col-md-6 col-sm-5">
								<div class="brows-job-position">
									<a href="{% url 'jobs:job_detail' job.slug %}"><h3> {{job.title}} </h3></a>
									<p>
										<span> {{job.category}} </span><span class="brows-job-sallery"><i class="fa fa-money"></i> {{job.salary}} </span>
										<span class="job-type cl-success bg-trans-success"> {{job.job_type}} </span>
									</p>
								</div>
							</div>
							<div class="col-md-3 col-sm-3">
								<div class="brows-job-location">
									<p><i class="fa fa-map-marker"></i>QBL Park, C40</p>
								</div>
							</div>
							<div class="col-md-2 col-sm-2">
								<div class="brows-job-link">
									<a href="{% url 'jobs:job_detail' job.slug %}" class="btn btn-default">Apply Now</a>
								</div>
							</div>
						</div>
						<span class="tg-themetag tg-featuretag"> {{job.published_at|date:'d M y'}} </span>
					</article>
				</div>
			{% endfor %}	
		

			<!--/.row-->
			{% if jobs.has_other_pages %}
				<div class="row">
					<ul class="pagination">
					{% if jobs.has_previous %}
						<li><a href="?page={{ jobs.previous_page_number }}">&laquo;</a></li>
					{% endif %}

					{% for i in jobs.paginator.page_range %}
						<li class="{% if i == jobs.number %} active {% endif %} "><a href="?page={{i}}">{{i}}</a></li>
					{% endfor %}
 
					{% if jobs.has_next %}
						<li><a href="?page={{ jobs.next_page_number }}">&raquo;</a></li> 
					{% endif %}
					</ul>
				</div>
			{% endif %}
		</div>
	</section>
	<!-- ========== Begin: Brows job Category End ===============  -->
{% endblock body %}	
			

templates/base_generic.html
{% extends 'base.html' %}
{% block body %}
{% load bootstrap4 %}

	<div class="clearfix"></div>
	
	<!-- Title Header Start -->
	<section class="col-md" style="padding: 150px" >
		{% block content %}


        {% endblock content %}
	</section>
	<div class=""></div>
	<!-- Title Header End -->
        

	
	<!-- Job full detail End -->
		
{% endblock body %}